Repository pimcore/google-marketing-bundle, pull requests merged in 2023-04, with the labels that each got.

#7 Adapt IndexSettingsListener for admin refactoring
  src/EventListener/IndexSettingsListener.php
Labels: Bug

#9 Adapt Master to Main changes
  public/js/report/googleSearchConsole/settings.js
  src/EventListener/Frontend/GoogleSearchConsoleVerificationListener.php
  src/PimcoreGoogleMarketingBundle.php
Labels: Task

#10 🔄 synced file(s) with pimcore/sync-common-files
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/system.yml
Labels: sync

#15 [Task] Add AdminBundle.
  composer.json
Labels: Task

#17 [Github Action] Setup php-cs-fixer
  .github/workflows/php-cs-fixer.yaml
  .gitignore
  .php-cs-fixer.dist.php
  src/EventListener/IndexSettingsListener.php
Labels: Task

#18 [Github Action] Setup PO editor sync
  .github/workflows/poeditor-export.yaml
Labels: Task

#19 [Github Action] Setup codeception
  .github/ci/files/config/bundles.php
  .github/ci/scripts/setup-pimcore-environment.sh
  .github/workflows/codeception.yml
  codeception.dist.yml
  composer.json
  tests/_bootstrap.php
  tests/bin/init-tests.sh
Labels: Task

#20 [Task]: Update system settings namespace
  src/SiteId/SiteId.php
Labels: Task

#22 [Pimcore 11] Exclude AdminBundle
  .github/ci/files/config/bundles.php
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/system.yml
  .github/workflows/static-analysis.yml
  .gitignore
  composer.json
  config/admin-classic.yaml
  config/pimcore/default.yaml
  phpstan-baseline.neon
  src/Controller/PortalController.php
  src/Controller/Reports/AnalyticsController.php
  src/Controller/ReportsControllerBase.php
  src/Controller/SettingsController.php
  src/DependencyInjection/PimcoreGoogleMarketingExtension.php
  src/PimcoreGoogleMarketingBundle.php
Labels: Task

#25 [Task] Add missing translation key
  translations/admin.en.yaml
Labels: Task
